// _dispatch.ts — Phase-9 + Phase-10 scrolling dispatch (47 properties:
// 3 scroll-timeline from Phase 9 + 44 long-tail from Phase 10).
import type { CSSProperties } from 'react';
// Phase-9 scroll-timeline (kept for back-compat with StyleBuilder.ts imports).
import { extractScrollTimeline } from './ScrollTimelineExtractor';
import { applyScrollTimeline } from './ScrollTimelineApplier';
import { extractScrollTimelineName } from './ScrollTimelineNameExtractor';
import { applyScrollTimelineName } from './ScrollTimelineNameApplier';
import { extractScrollTimelineAxis } from './ScrollTimelineAxisExtractor';
import { applyScrollTimelineAxis } from './ScrollTimelineAxisApplier';
import { extractScrollBehavior } from './ScrollBehaviorExtractor';
import { applyScrollBehavior } from './ScrollBehaviorApplier';
import { extractScrollSnapType } from './ScrollSnapTypeExtractor';
import { applyScrollSnapType } from './ScrollSnapTypeApplier';
import { extractScrollSnapAlign } from './ScrollSnapAlignExtractor';
import { applyScrollSnapAlign } from './ScrollSnapAlignApplier';
import { extractScrollSnapStop } from './ScrollSnapStopExtractor';
import { applyScrollSnapStop } from './ScrollSnapStopApplier';
import { extractScrollPadding } from './ScrollPaddingExtractor';
import { applyScrollPadding } from './ScrollPaddingApplier';
import { extractScrollPaddingTop } from './ScrollPaddingTopExtractor';
import { applyScrollPaddingTop } from './ScrollPaddingTopApplier';
import { extractScrollPaddingRight } from './ScrollPaddingRightExtractor';
import { applyScrollPaddingRight } from './ScrollPaddingRightApplier';
import { extractScrollPaddingBottom } from './ScrollPaddingBottomExtractor';
import { applyScrollPaddingBottom } from './ScrollPaddingBottomApplier';
import { extractScrollPaddingLeft } from './ScrollPaddingLeftExtractor';
import { applyScrollPaddingLeft } from './ScrollPaddingLeftApplier';
import { extractScrollPaddingBlock } from './ScrollPaddingBlockExtractor';
import { applyScrollPaddingBlock } from './ScrollPaddingBlockApplier';
import { extractScrollPaddingBlockStart } from './ScrollPaddingBlockStartExtractor';
import { applyScrollPaddingBlockStart } from './ScrollPaddingBlockStartApplier';
import { extractScrollPaddingBlockEnd } from './ScrollPaddingBlockEndExtractor';
import { applyScrollPaddingBlockEnd } from './ScrollPaddingBlockEndApplier';
import { extractScrollPaddingInline } from './ScrollPaddingInlineExtractor';
import { applyScrollPaddingInline } from './ScrollPaddingInlineApplier';
import { extractScrollPaddingInlineStart } from './ScrollPaddingInlineStartExtractor';
import { applyScrollPaddingInlineStart } from './ScrollPaddingInlineStartApplier';
import { extractScrollPaddingInlineEnd } from './ScrollPaddingInlineEndExtractor';
import { applyScrollPaddingInlineEnd } from './ScrollPaddingInlineEndApplier';
import { extractScrollMargin } from './ScrollMarginExtractor';
import { applyScrollMargin } from './ScrollMarginApplier';
import { extractScrollMarginTop } from './ScrollMarginTopExtractor';
import { applyScrollMarginTop } from './ScrollMarginTopApplier';
import { extractScrollMarginRight } from './ScrollMarginRightExtractor';
import { applyScrollMarginRight } from './ScrollMarginRightApplier';
import { extractScrollMarginBottom } from './ScrollMarginBottomExtractor';
import { applyScrollMarginBottom } from './ScrollMarginBottomApplier';
import { extractScrollMarginLeft } from './ScrollMarginLeftExtractor';
import { applyScrollMarginLeft } from './ScrollMarginLeftApplier';
import { extractScrollMarginBlock } from './ScrollMarginBlockExtractor';
import { applyScrollMarginBlock } from './ScrollMarginBlockApplier';
import { extractScrollMarginBlockStart } from './ScrollMarginBlockStartExtractor';
import { applyScrollMarginBlockStart } from './ScrollMarginBlockStartApplier';
import { extractScrollMarginBlockEnd } from './ScrollMarginBlockEndExtractor';
import { applyScrollMarginBlockEnd } from './ScrollMarginBlockEndApplier';
import { extractScrollMarginInline } from './ScrollMarginInlineExtractor';
import { applyScrollMarginInline } from './ScrollMarginInlineApplier';
import { extractScrollMarginInlineStart } from './ScrollMarginInlineStartExtractor';
import { applyScrollMarginInlineStart } from './ScrollMarginInlineStartApplier';
import { extractScrollMarginInlineEnd } from './ScrollMarginInlineEndExtractor';
import { applyScrollMarginInlineEnd } from './ScrollMarginInlineEndApplier';
import { extractOverscrollBehavior } from './OverscrollBehaviorExtractor';
import { applyOverscrollBehavior } from './OverscrollBehaviorApplier';
import { extractOverscrollBehaviorX } from './OverscrollBehaviorXExtractor';
import { applyOverscrollBehaviorX } from './OverscrollBehaviorXApplier';
import { extractOverscrollBehaviorY } from './OverscrollBehaviorYExtractor';
import { applyOverscrollBehaviorY } from './OverscrollBehaviorYApplier';
import { extractOverscrollBehaviorBlock } from './OverscrollBehaviorBlockExtractor';
import { applyOverscrollBehaviorBlock } from './OverscrollBehaviorBlockApplier';
import { extractOverscrollBehaviorInline } from './OverscrollBehaviorInlineExtractor';
import { applyOverscrollBehaviorInline } from './OverscrollBehaviorInlineApplier';
import { extractScrollbarWidth } from './ScrollbarWidthExtractor';
import { applyScrollbarWidth } from './ScrollbarWidthApplier';
import { extractScrollbarColor } from './ScrollbarColorExtractor';
import { applyScrollbarColor } from './ScrollbarColorApplier';
import { extractScrollbarGutter } from './ScrollbarGutterExtractor';
import { applyScrollbarGutter } from './ScrollbarGutterApplier';
import { extractOverflowAnchor } from './OverflowAnchorExtractor';
import { applyOverflowAnchor } from './OverflowAnchorApplier';
import { extractOverflowClipMargin } from './OverflowClipMarginExtractor';
import { applyOverflowClipMargin } from './OverflowClipMarginApplier';
import { extractScrollStart } from './ScrollStartExtractor';
import { applyScrollStart } from './ScrollStartApplier';
import { extractScrollStartX } from './ScrollStartXExtractor';
import { applyScrollStartX } from './ScrollStartXApplier';
import { extractScrollStartY } from './ScrollStartYExtractor';
import { applyScrollStartY } from './ScrollStartYApplier';
import { extractScrollStartBlock } from './ScrollStartBlockExtractor';
import { applyScrollStartBlock } from './ScrollStartBlockApplier';
import { extractScrollStartInline } from './ScrollStartInlineExtractor';
import { applyScrollStartInline } from './ScrollStartInlineApplier';
import { extractScrollStartTarget } from './ScrollStartTargetExtractor';
import { applyScrollStartTarget } from './ScrollStartTargetApplier';
import { extractScrollMarkerGroup } from './ScrollMarkerGroupExtractor';
import { applyScrollMarkerGroup } from './ScrollMarkerGroupApplier';
import { extractScrollTargetGroup } from './ScrollTargetGroupExtractor';
import { applyScrollTargetGroup } from './ScrollTargetGroupApplier';
interface IRPropertyLike { type: string; data: unknown }

// Back-compat export used by StyleBuilder (Phase 9 only knew these three).
export function applyScrollingPhase9(properties: IRPropertyLike[]): CSSProperties {
  const out: CSSProperties = {};
  Object.assign(out, applyScrollTimeline(extractScrollTimeline(properties)));
  Object.assign(out, applyScrollTimelineName(extractScrollTimelineName(properties)));
  Object.assign(out, applyScrollTimelineAxis(extractScrollTimelineAxis(properties)));
  return out;
}

export function applyScrollingPhase10(properties: IRPropertyLike[]): CSSProperties {
  const out: CSSProperties = {};
  Object.assign(out, applyScrollBehavior(extractScrollBehavior(properties)));
  Object.assign(out, applyScrollSnapType(extractScrollSnapType(properties)));
  Object.assign(out, applyScrollSnapAlign(extractScrollSnapAlign(properties)));
  Object.assign(out, applyScrollSnapStop(extractScrollSnapStop(properties)));
  Object.assign(out, applyScrollPadding(extractScrollPadding(properties)));
  Object.assign(out, applyScrollPaddingTop(extractScrollPaddingTop(properties)));
  Object.assign(out, applyScrollPaddingRight(extractScrollPaddingRight(properties)));
  Object.assign(out, applyScrollPaddingBottom(extractScrollPaddingBottom(properties)));
  Object.assign(out, applyScrollPaddingLeft(extractScrollPaddingLeft(properties)));
  Object.assign(out, applyScrollPaddingBlock(extractScrollPaddingBlock(properties)));
  Object.assign(out, applyScrollPaddingBlockStart(extractScrollPaddingBlockStart(properties)));
  Object.assign(out, applyScrollPaddingBlockEnd(extractScrollPaddingBlockEnd(properties)));
  Object.assign(out, applyScrollPaddingInline(extractScrollPaddingInline(properties)));
  Object.assign(out, applyScrollPaddingInlineStart(extractScrollPaddingInlineStart(properties)));
  Object.assign(out, applyScrollPaddingInlineEnd(extractScrollPaddingInlineEnd(properties)));
  Object.assign(out, applyScrollMargin(extractScrollMargin(properties)));
  Object.assign(out, applyScrollMarginTop(extractScrollMarginTop(properties)));
  Object.assign(out, applyScrollMarginRight(extractScrollMarginRight(properties)));
  Object.assign(out, applyScrollMarginBottom(extractScrollMarginBottom(properties)));
  Object.assign(out, applyScrollMarginLeft(extractScrollMarginLeft(properties)));
  Object.assign(out, applyScrollMarginBlock(extractScrollMarginBlock(properties)));
  Object.assign(out, applyScrollMarginBlockStart(extractScrollMarginBlockStart(properties)));
  Object.assign(out, applyScrollMarginBlockEnd(extractScrollMarginBlockEnd(properties)));
  Object.assign(out, applyScrollMarginInline(extractScrollMarginInline(properties)));
  Object.assign(out, applyScrollMarginInlineStart(extractScrollMarginInlineStart(properties)));
  Object.assign(out, applyScrollMarginInlineEnd(extractScrollMarginInlineEnd(properties)));
  Object.assign(out, applyOverscrollBehavior(extractOverscrollBehavior(properties)));
  Object.assign(out, applyOverscrollBehaviorX(extractOverscrollBehaviorX(properties)));
  Object.assign(out, applyOverscrollBehaviorY(extractOverscrollBehaviorY(properties)));
  Object.assign(out, applyOverscrollBehaviorBlock(extractOverscrollBehaviorBlock(properties)));
  Object.assign(out, applyOverscrollBehaviorInline(extractOverscrollBehaviorInline(properties)));
  Object.assign(out, applyScrollbarWidth(extractScrollbarWidth(properties)));
  Object.assign(out, applyScrollbarColor(extractScrollbarColor(properties)));
  Object.assign(out, applyScrollbarGutter(extractScrollbarGutter(properties)));
  Object.assign(out, applyOverflowAnchor(extractOverflowAnchor(properties)));
  Object.assign(out, applyOverflowClipMargin(extractOverflowClipMargin(properties)));
  Object.assign(out, applyScrollStart(extractScrollStart(properties)));
  Object.assign(out, applyScrollStartX(extractScrollStartX(properties)));
  Object.assign(out, applyScrollStartY(extractScrollStartY(properties)));
  Object.assign(out, applyScrollStartBlock(extractScrollStartBlock(properties)));
  Object.assign(out, applyScrollStartInline(extractScrollStartInline(properties)));
  Object.assign(out, applyScrollStartTarget(extractScrollStartTarget(properties)));
  Object.assign(out, applyScrollMarkerGroup(extractScrollMarkerGroup(properties)));
  Object.assign(out, applyScrollTargetGroup(extractScrollTargetGroup(properties)));
  return out;
}
