package com.styleconverter.runtime

/**
 * Ownership map of IR property-type strings → the category folder whose
 * triplet claims them, e.g.
 *   `PropertyRegistry.migrated("BorderTopWidth", owner = "borders/sides")`
 *
 * ## What this is on Compose — READ BEFORE TRUSTING IT (retro sweep P2a, A6#8)
 *
 * A TEST/AUDIT ARTIFACT, not a dispatch mechanism. The header this replaces
 * claimed "the legacy monolithic [StyleApplier] dispatch switch consults this
 * registry so it can skip properties a new extractor has already claimed".
 * It does not, and never did on this platform: `grep -rn 'PropertyRegistry\.'`
 * over `runtimes/compose/src/main` + `apps/android-harness/app/src/main`
 * returns only the extractors' own `migrated(...)` registration lines and
 * doc comments. Dispatch is inline in [StyleApplier] and ComponentRenderer.
 * [isMigrated], [ownerOf] and [allRegistered] have production-call-count ZERO
 * (18 / 43 / 1 references, all from `src/test`), and so does every
 * `*Registration.kt` object: a Kotlin `object`'s init block runs on FIRST
 * TOUCH, so in a production render nothing touches them and nothing they
 * claim is ever registered. The map is populated only inside a test JVM that
 * names the objects.
 *
 * Consequence for coverage: `allRegistered()` is NOT the source of Compose's
 * "registered 558/558" — `tools/visual/coverage-audit.mjs` scrapes the IR type
 * name as a quoted STRING anywhere under the engine root, which is why a
 * registration claim can outlive the applier it named. iOS and web do consult
 * their registries at render time (StyleBuilder.swift's
 * `PropertyRegistry.migrated.contains`, web StyleBuilder.ts's
 * `isLegacyProperty`); Compose does not.
 *
 * The functions below are kept because the per-category registry tests pin
 * them (they are the only executable check that a category's claims and its
 * IR-name list agree). Do not read them as evidence that a property renders.
 *
 * Rules that still hold:
 *  - IR property names are matched case-sensitively (they're the IRProperty.type
 *    values the CSS parser emits, e.g. "BorderTopWidth", not "border-top-width").
 *  - Registration is idempotent; re-registering the same property is a no-op.
 *  - The `owner` string is just the folder path (e.g. "borders/sides",
 *    "effects/shadow") for introspection / `allRegistered()` reports.
 */
object PropertyRegistry {

    // Backing map: IR property type -> owning category folder (e.g. "borders/sides").
    // Using a linkedMap so allRegistered() enumerates in registration order,
    // which makes the coverage report stable across runs.
    private val migrated: MutableMap<String, String> = linkedMapOf()

    /**
     * Register one or more IR property names as migrated to the canonical
     * style-engine pattern. Called from each extractor's init block or
     * companion object so the registry is populated at class-load time.
     *
     * @param propertyTypes One or more IRProperty.type strings (CSS camelcase:
     *                      "BorderTopWidth", "BorderImageSource", etc.)
     * @param owner Folder path under style/ that owns these properties.
     *              Used only for introspection; no behavioral effect.
     */
    @Synchronized
    fun migrated(vararg propertyTypes: String, owner: String) {
        // Idempotent insert: if the property has already been claimed by
        // another extractor, keep the first owner (first-write-wins). This
        // catches accidental double-registration during the migration.
        for (t in propertyTypes) {
            migrated.putIfAbsent(t, owner)
        }
    }

    /**
     * @return true if [propertyType] has been claimed by a registration
     *         object that this JVM has touched. TEST-ONLY on Compose (A6#8):
     *         no production caller — the "legacy StyleApplier switch uses
     *         this to skip the property" claim that stood here was false.
     */
    @Synchronized
    fun isMigrated(propertyType: String): Boolean = propertyType in migrated

    /**
     * @return the category folder that owns [propertyType], or null if the
     *         property has not yet been migrated.
     */
    @Synchronized
    fun ownerOf(propertyType: String): String? = migrated[propertyType]

    /**
     * @return an immutable snapshot of all registered (propertyType -> owner)
     *         pairs. TEST-ONLY (A6#8): there is no debug overlay and no
     *         `testing/README.md` — that tree was renamed to `runtimes/` in
     *         the wave-5 restructure. The coverage matrix
     *         (tools/visual/COVERAGE.md) is generated by scraping FILES, not
     *         by running this, so nothing here bounds it.
     */
    @Synchronized
    fun allRegistered(): Map<String, String> = migrated.toMap()

    /**
     * @return the number of migrated properties. Cheap way to assert progress
     *         in unit tests ("after Phase 5, expect ≥ 47 border properties").
     */
    @Synchronized
    fun size(): Int = migrated.size

    /**
     * Reset the registry. Used by tests that need to re-register extractors
     * in a clean state — never called in production code.
     */
    @Synchronized
    fun reset() {
        migrated.clear()
    }
}
