package app.irmodels.properties.color

import app.irmodels.*
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the CSS `accent-color` property.
 *
 * ## CSS Property
 * **Syntax**: `accent-color: auto | <color>`
 *
 * ## Description
 * Sets the accent color for user-interface controls generated by the element.
 * Used for checkboxes, radio buttons, range sliders, and progress elements.
 *
 * @property color The accent color value
 * @see [MDN accent-color](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color)
 */
@Serializable
data class AccentColorProperty(
    val color: AccentColor
) : IRProperty {
    override val propertyName = "accent-color"

    @Serializable
    sealed interface AccentColor {
        @Serializable
        @SerialName("auto")
        data class Auto(val unit: Unit = Unit) : AccentColor

        @Serializable
        @SerialName("color")
        data class Color(val value: IRColor) : AccentColor
    }
}
