// _dispatch.ts — Phase-10 speech long-tail dispatch (30 properties).
import type { CSSProperties } from 'react';
import { extractVolume } from './VolumeExtractor';
import { applyVolume } from './VolumeApplier';
import { extractSpeak } from './SpeakExtractor';
import { applySpeak } from './SpeakApplier';
import { extractSpeakAs } from './SpeakAsExtractor';
import { applySpeakAs } from './SpeakAsApplier';
import { extractSpeakHeader } from './SpeakHeaderExtractor';
import { applySpeakHeader } from './SpeakHeaderApplier';
import { extractSpeakNumeral } from './SpeakNumeralExtractor';
import { applySpeakNumeral } from './SpeakNumeralApplier';
import { extractSpeakPunctuation } from './SpeakPunctuationExtractor';
import { applySpeakPunctuation } from './SpeakPunctuationApplier';
import { extractPause } from './PauseExtractor';
import { applyPause } from './PauseApplier';
import { extractPauseBefore } from './PauseBeforeExtractor';
import { applyPauseBefore } from './PauseBeforeApplier';
import { extractPauseAfter } from './PauseAfterExtractor';
import { applyPauseAfter } from './PauseAfterApplier';
import { extractRest } from './RestExtractor';
import { applyRest } from './RestApplier';
import { extractRestBefore } from './RestBeforeExtractor';
import { applyRestBefore } from './RestBeforeApplier';
import { extractRestAfter } from './RestAfterExtractor';
import { applyRestAfter } from './RestAfterApplier';
import { extractCue } from './CueExtractor';
import { applyCue } from './CueApplier';
import { extractCueBefore } from './CueBeforeExtractor';
import { applyCueBefore } from './CueBeforeApplier';
import { extractCueAfter } from './CueAfterExtractor';
import { applyCueAfter } from './CueAfterApplier';
import { extractVoiceFamily } from './VoiceFamilyExtractor';
import { applyVoiceFamily } from './VoiceFamilyApplier';
import { extractVoiceRate } from './VoiceRateExtractor';
import { applyVoiceRate } from './VoiceRateApplier';
import { extractVoicePitch } from './VoicePitchExtractor';
import { applyVoicePitch } from './VoicePitchApplier';
import { extractVoiceRange } from './VoiceRangeExtractor';
import { applyVoiceRange } from './VoiceRangeApplier';
import { extractVoiceStress } from './VoiceStressExtractor';
import { applyVoiceStress } from './VoiceStressApplier';
import { extractVoiceVolume } from './VoiceVolumeExtractor';
import { applyVoiceVolume } from './VoiceVolumeApplier';
import { extractVoiceDuration } from './VoiceDurationExtractor';
import { applyVoiceDuration } from './VoiceDurationApplier';
import { extractVoiceBalance } from './VoiceBalanceExtractor';
import { applyVoiceBalance } from './VoiceBalanceApplier';
import { extractPitch } from './PitchExtractor';
import { applyPitch } from './PitchApplier';
import { extractPitchRange } from './PitchRangeExtractor';
import { applyPitchRange } from './PitchRangeApplier';
import { extractRichness } from './RichnessExtractor';
import { applyRichness } from './RichnessApplier';
import { extractStress } from './StressExtractor';
import { applyStress } from './StressApplier';
import { extractSpeechRate } from './SpeechRateExtractor';
import { applySpeechRate } from './SpeechRateApplier';
import { extractAzimuth } from './AzimuthExtractor';
import { applyAzimuth } from './AzimuthApplier';
import { extractElevation } from './ElevationExtractor';
import { applyElevation } from './ElevationApplier';
interface IRPropertyLike { type: string; data: unknown }
export function applySpeechPhase10(properties: IRPropertyLike[]): CSSProperties {
  const out: CSSProperties = {};
  Object.assign(out, applyVolume(extractVolume(properties)));
  Object.assign(out, applySpeak(extractSpeak(properties)));
  Object.assign(out, applySpeakAs(extractSpeakAs(properties)));
  Object.assign(out, applySpeakHeader(extractSpeakHeader(properties)));
  Object.assign(out, applySpeakNumeral(extractSpeakNumeral(properties)));
  Object.assign(out, applySpeakPunctuation(extractSpeakPunctuation(properties)));
  Object.assign(out, applyPause(extractPause(properties)));
  Object.assign(out, applyPauseBefore(extractPauseBefore(properties)));
  Object.assign(out, applyPauseAfter(extractPauseAfter(properties)));
  Object.assign(out, applyRest(extractRest(properties)));
  Object.assign(out, applyRestBefore(extractRestBefore(properties)));
  Object.assign(out, applyRestAfter(extractRestAfter(properties)));
  Object.assign(out, applyCue(extractCue(properties)));
  Object.assign(out, applyCueBefore(extractCueBefore(properties)));
  Object.assign(out, applyCueAfter(extractCueAfter(properties)));
  Object.assign(out, applyVoiceFamily(extractVoiceFamily(properties)));
  Object.assign(out, applyVoiceRate(extractVoiceRate(properties)));
  Object.assign(out, applyVoicePitch(extractVoicePitch(properties)));
  Object.assign(out, applyVoiceRange(extractVoiceRange(properties)));
  Object.assign(out, applyVoiceStress(extractVoiceStress(properties)));
  Object.assign(out, applyVoiceVolume(extractVoiceVolume(properties)));
  Object.assign(out, applyVoiceDuration(extractVoiceDuration(properties)));
  Object.assign(out, applyVoiceBalance(extractVoiceBalance(properties)));
  Object.assign(out, applyPitch(extractPitch(properties)));
  Object.assign(out, applyPitchRange(extractPitchRange(properties)));
  Object.assign(out, applyRichness(extractRichness(properties)));
  Object.assign(out, applyStress(extractStress(properties)));
  Object.assign(out, applySpeechRate(extractSpeechRate(properties)));
  Object.assign(out, applyAzimuth(extractAzimuth(properties)));
  Object.assign(out, applyElevation(extractElevation(properties)));
  return out;
}
