package com.styleconverter.runtime.table

import androidx.compose.ui.Modifier
import com.styleconverter.runtime.core.ir.IRComponent
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotSame
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * wave-54 lane L2 (TB-android) — pins for [TableCellHug]: the chrome of the
 * one table box this runtime fabricates (TableBodyForest's anonymous table,
 * CSS 2.1 §17.2.1) and TableApplier's half of its wiring. The renderer's half
 * (ComponentRenderer's `DisplayType.TABLE ->` arm spends `chrome`) is pinned
 * by TableCellHugSeamWiringTest, which ships inside the lane's seam patch.
 *
 * Payloads VERBATIM from tools/titan/runs/wave53-final/sections/<section>/per-test-ir/
 * (byte-identical in wave54-open), generated by
 * tools/titan/results/wave54-table-body-cell/gen-pins.py — decoded and
 * slot-composed exactly as the harness does.
 *
 * WHY each row: the synthetic table is the ONLY box whose chrome changes
 * (no demo stroke, cells hug); every other Compose table — a declared
 * `display: table` (006's own body-root, percentage-sizing-003: the 396-px
 * rim the general fix would remove, queued), a UA `<table>` (baseline-empty-
 * cell-001, contain-content-004: L4's carrier, PLAN §9 D15) — keeps today's
 * stroke expression and hug = false, so it renders byte-identically.
 *
 * EXECUTED MUTATIONS (lane note §"Pins and executed mutations"; each source
 * restored byte-exact, sha256 logged):
 *   T1 `stroke = fabricatedDefault` (drop `!anonymous`)     → the synthetic row red.
 *   T2 `hug = false`                                        → the synthetic row red.
 *   T3 `hug = true` for every table                         → the four declared/UA rows red.
 *   T4 hugColumn(false) no longer returns its receiver      → the identity pin red.
 *   T5 TableCell without `.hugColumn(…)`                    → the applier source pin red.
 *   T6 Table without the LocalTableCellsHugContent provider → the applier source pin red.
 *   m6 (TableBodyForest) the synthetic boxes lose the role  → the synthetic row and the fold pin red.
 */
class TableCellHugTest {

    /** Decode + slot-compose a v2 document exactly as the harness does. */
    private fun rootsOf(componentsJson: String): List<IRComponent> =
        com.styleconverter.runtime.core.renderer.SlotComposer.compose(
            com.styleconverter.runtime.core.ir.IRDocumentDecoder.decode(
                """{"irVersion":2,"minReaderVersion":2,"components":[$componentsJson]}"""))

    /**
     * ComponentRenderer.kt's frozen `fabricatedCellBorder` expression (the
     * `DisplayType.TABLE ->` arm, wave 38) under WPT capture — what the seam
     * passes as `fabricatedDefault`, verbatim (TableCellHugSeamWiringTest).
     */
    private fun todaysStroke(c: IRComponent): Boolean = !(true &&           // LocalWptCaptureMode.current
        c.properties.none { it.type == "Display" } &&                       // no declared display
        TableBoxTree.uaRoleOf(c._tag) == TableBoxTree.Role.TABLE)          // a UA <table>

    /** CSS2/css21-errata/s-11-1-1b-006 — all four roots (`body { display: table }`). */
    private val s006 = """
        {"id":"wpt__css2__css21-errata__s-11-1-1b-006__0-141","name":"wpt__CSS2__css21-errata__s-11-1-1b-006__0","properties":[{"type":"OverflowX","data":"HIDDEN"},{"type":"OverflowY","data":"HIDDEN"},{"type":"Display","data":"TABLE"},{"type":"BorderSpacing","data":{"type":"single","px":0}},{"type":"MarginTop","data":{"px":40}},{"type":"MarginRight","data":{"px":8}},{"type":"MarginBottom","data":{"px":8}},{"type":"MarginLeft","data":{"px":8}}],"meta":{"role":"body-root"}},
        {"id":"wpt__css2__css21-errata__s-11-1-1b-006__1-142","name":"wpt__CSS2__css21-errata__s-11-1-1b-006__1","properties":[{"type":"Generic","data":{"propertyName":"display","rawValue":"caption","_unmapped":true}},{"type":"MarginBottom","data":{"px":10}}],"meta":{"role":"ws-after"}},
        {"id":"wpt__css2__css21-errata__s-11-1-1b-006__2-143","name":"wpt__CSS2__css21-errata__s-11-1-1b-006__2","properties":[{"type":"Display","data":"TABLE_CELL"},{"type":"Width","data":{"type":"length","px":20}},{"type":"Height","data":{"type":"length","px":20}},{"type":"MarginTop","data":{"px":-15}},{"type":"BackgroundColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}}],"meta":{"role":"ws-after"}},
        {"id":"wpt__css2__css21-errata__s-11-1-1b-006__3-144","name":"wpt__CSS2__css21-errata__s-11-1-1b-006__3","properties":[{"type":"Position","data":"ABSOLUTE"},{"type":"Top","data":{"px":0}},{"type":"Left","data":{"px":8}}],"text":"Test passes if there is a black square below.","meta":{"sourceTag":"p"}}
    """.trimIndent()

    /** css-tables/height-distribution/percentage-sizing-of-table-cell-children-003 — a declared `display: table`. */
    private val pct003 = """
        {"id":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__0-279","name":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__0","properties":[],"text":"Test passes if there is a filled green square and no red.","meta":{"sourceTag":"p","role":"ws-after"}},
        {"id":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__1-280","name":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__1","properties":[{"type":"Height","data":{"type":"length","px":100}},{"type":"Width","data":{"type":"length","px":100}},{"type":"BackgroundColor","data":{"srgb":{"r":1,"g":0,"b":0},"original":"red"}},{"type":"Position","data":"ABSOLUTE"},{"type":"ZIndex","data":{"value":-1,"original":{"type":"integer","value":-1}}}],"meta":{"role":"ws-after"}},
        {"id":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__2-281","name":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__2","properties":[{"type":"Display","data":"TABLE"}]},
        {"id":"height-distribution__percentage-sizing-of-table-cell-children-003__2__0-282","name":"height-distribution__percentage-sizing-of-table-cell-children-003__2__0","properties":[{"type":"Display","data":"TABLE_CELL"},{"type":"Height","data":{"type":"percentage","value":100}}],"slot":{"parent":"wpt__css-tables__height-distribution__percentage-sizing-of-table-cell-children-003__2-281"}},
        {"id":"height-distribution__percentage-sizing-of-table-cell-children-003__2__0__0-283","name":"height-distribution__percentage-sizing-of-table-cell-children-003__2__0__0","properties":[{"type":"OverflowY","data":"AUTO"},{"type":"Height","data":{"type":"percentage","value":100}},{"type":"Width","data":{"type":"length","px":100}},{"type":"MinHeight","data":{"type":"length","px":100}},{"type":"BackgroundColor","data":{"srgb":{"r":0,"g":0.5019607843137255,"b":0},"original":"green"}}],"slot":{"parent":"height-distribution__percentage-sizing-of-table-cell-children-003__2__0-282"}}
    """.trimIndent()

    /** css-tables/baseline-empty-cell-001 — a UA `<table>` (no declared display). */
    private val bec001 = """
        {"id":"wpt__css-tables__baseline-empty-cell-001__0-072","name":"wpt__css-tables__baseline-empty-cell-001__0","properties":[{"type":"BorderCollapse","data":"COLLAPSE"}],"meta":{"sourceTag":"table"}},
        {"id":"baseline-empty-cell-001__0__0-073","name":"baseline-empty-cell-001__0__0","properties":[{"type":"VerticalAlign","data":{"type":"keyword","value":"BASELINE"}}],"slot":{"parent":"wpt__css-tables__baseline-empty-cell-001__0-072"},"meta":{"sourceTag":"tr"}},
        {"id":"baseline-empty-cell-001__0__0__0-074","name":"baseline-empty-cell-001__0__0__0","properties":[{"type":"Height","data":{"type":"length","px":30}},{"type":"BorderTopWidth","data":{"px":1}},{"type":"BorderRightWidth","data":{"px":1}},{"type":"BorderBottomWidth","data":{"px":1}},{"type":"BorderLeftWidth","data":{"px":1}},{"type":"BorderTopStyle","data":"SOLID"},{"type":"BorderRightStyle","data":"SOLID"},{"type":"BorderBottomStyle","data":"SOLID"},{"type":"BorderLeftStyle","data":"SOLID"},{"type":"BorderTopColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"BorderRightColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"BorderBottomColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"BorderLeftColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"PaddingTop","data":{"px":1}},{"type":"PaddingRight","data":{"px":1}},{"type":"PaddingBottom","data":{"px":1}},{"type":"PaddingLeft","data":{"px":1}}],"slot":{"parent":"baseline-empty-cell-001__0__0-073"},"text":"ABCDE","meta":{"sourceTag":"td"}},
        {"id":"baseline-empty-cell-001__0__0__1-075","name":"baseline-empty-cell-001__0__0__1","properties":[{"type":"Height","data":{"type":"length","px":30}},{"type":"BorderTopWidth","data":{"px":1}},{"type":"BorderRightWidth","data":{"px":1}},{"type":"BorderBottomWidth","data":{"px":1}},{"type":"BorderLeftWidth","data":{"px":1}},{"type":"BorderTopStyle","data":"SOLID"},{"type":"BorderRightStyle","data":"SOLID"},{"type":"BorderBottomStyle","data":"SOLID"},{"type":"BorderLeftStyle","data":"SOLID"},{"type":"BorderTopColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"BorderRightColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"BorderBottomColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"BorderLeftColor","data":{"srgb":{"r":0,"g":0,"b":0},"original":"black"}},{"type":"PaddingTop","data":{"px":1}},{"type":"PaddingRight","data":{"px":1}},{"type":"PaddingBottom","data":{"px":1}},{"type":"PaddingLeft","data":{"px":1}}],"slot":{"parent":"baseline-empty-cell-001__0__0-073"},"meta":{"sourceTag":"td"}}
    """.trimIndent()

    /** css-contain/contain-content-004 — a UA `<table>`, L4's OOF carrier (D2 radius, PLAN §9 D15). */
    private val cc004 = """
        {"id":"wpt__css-contain__contain-content-004__0-048","name":"wpt__css-contain__contain-content-004__0","properties":[],"text":"Test passes if there is the word PASS and if there is no red.","meta":{"sourceTag":"p"}},
        {"id":"wpt__css-contain__contain-content-004__1-049","name":"wpt__css-contain__contain-content-004__1","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":0,"g":0,"b":1},"original":"blue"}},{"type":"BorderSpacing","data":{"type":"single","px":2}},{"type":"Height","data":{"type":"length","px":206}},{"type":"TableLayout","data":"FIXED"},{"type":"Width","data":{"type":"length","px":206}}],"meta":{"sourceTag":"table"}},
        {"id":"contain-content-004__1__0-050","name":"contain-content-004__1__0","properties":[],"slot":{"parent":"wpt__css-contain__contain-content-004__1-049"},"meta":{"sourceTag":"tr"}},
        {"id":"contain-content-004__1__0__0-051","name":"contain-content-004__1__0__0","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":1,"g":1,"b":1},"original":"white"}},{"type":"PaddingTop","data":{"px":0}},{"type":"PaddingRight","data":{"px":0}},{"type":"PaddingBottom","data":{"px":0}},{"type":"PaddingLeft","data":{"px":0}},{"type":"VerticalAlign","data":{"type":"keyword","value":"TOP"}}],"slot":{"parent":"contain-content-004__1__0-050"},"text":" ","meta":{"sourceTag":"td"}},
        {"id":"contain-content-004__1__0__1-052","name":"contain-content-004__1__0__1","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":1,"g":1,"b":1},"original":"white"}},{"type":"PaddingTop","data":{"px":0}},{"type":"PaddingRight","data":{"px":0}},{"type":"PaddingBottom","data":{"px":0}},{"type":"PaddingLeft","data":{"px":0}},{"type":"VerticalAlign","data":{"type":"keyword","value":"TOP"}}],"slot":{"parent":"contain-content-004__1__0-050"},"text":" ","meta":{"sourceTag":"td"}},
        {"id":"contain-content-004__1__1-053","name":"contain-content-004__1__1","properties":[],"slot":{"parent":"wpt__css-contain__contain-content-004__1-049"},"meta":{"sourceTag":"tr"}},
        {"id":"contain-content-004__1__1__0-054","name":"contain-content-004__1__1__0","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":1,"g":1,"b":1},"original":"white"}},{"type":"PaddingTop","data":{"px":0}},{"type":"PaddingRight","data":{"px":0}},{"type":"PaddingBottom","data":{"px":0}},{"type":"PaddingLeft","data":{"px":0}},{"type":"VerticalAlign","data":{"type":"keyword","value":"TOP"}}],"slot":{"parent":"contain-content-004__1__1-053"},"text":" ","meta":{"sourceTag":"td"}},
        {"id":"contain-content-004__1__1__1-055","name":"contain-content-004__1__1__1","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":1,"g":1,"b":1},"original":"white"}},{"type":"PaddingTop","data":{"px":0}},{"type":"PaddingRight","data":{"px":0}},{"type":"PaddingBottom","data":{"px":0}},{"type":"PaddingLeft","data":{"px":0}},{"type":"VerticalAlign","data":{"type":"keyword","value":"TOP"}},{"type":"Contain","data":["CONTENT"]}],"slot":{"parent":"contain-content-004__1__1-053"},"meta":{"sourceTag":"td"}},
        {"id":"contain-content-004__1__1__1__0-056","name":"contain-content-004__1__1__1__0","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":1,"g":0,"b":0},"original":"red"}},{"type":"Color","data":{"srgb":{"r":1,"g":1,"b":0},"original":"yellow"}},{"type":"FontFamily","data":["monospace"]},{"type":"VerticalAlign","data":{"type":"keyword","value":"TOP"}}],"slot":{"parent":"contain-content-004__1__1__1-055"},"text":"FAIL","meta":{"sourceTag":"span"}},
        {"id":"contain-content-004__1__1__1__1-057","name":"contain-content-004__1__1__1__1","properties":[{"type":"BackgroundColor","data":{"srgb":{"r":0,"g":0.5019607843137255,"b":0},"original":"green"}},{"type":"Color","data":{"srgb":{"r":1,"g":1,"b":1},"original":"white"}},{"type":"FontFamily","data":["monospace"]},{"type":"Left","data":{"px":0}},{"type":"Position","data":"ABSOLUTE"},{"type":"Top","data":{"px":0}}],"slot":{"parent":"contain-content-004__1__1__1-055"},"text":"PASS"}
    """.trimIndent()

    /** The synthetic table the composed canvas renders for 006 (TableBodyForest, §17.2.1 rule 2). */
    private val syntheticTable: IRComponent by lazy { TableBodyForest.rewrite(rootsOf(s006))[1] }

    @Test
    fun anonymousTable_noStroke_cellsHug() {
        // The forest's synthetic box — today's expression says "stroke" (it
        // declares Display and has no _tag); §17.2.1 says no border.
        val t = syntheticTable
        assertEquals("wpt__css2__css21-errata__s-11-1-1b-006__0-141#table", t.id)
        assertTrue(todaysStroke(t))
        assertEquals(TableCellHug.Chrome(stroke = false, hug = true), TableCellHug.chrome(t, todaysStroke(t)))
    }

    @Test
    fun anonymousMarker_survivesTheRenderersPreDisplayFolds() {
        // RenderComponent rebinds `component` through these folds before its
        // display switch reaches the TABLE arm the seam lives in
        // (ContentsUnboxing → PseudoTextFold → PseudoBoxFold, then
        // `copy(properties = effectiveProperties)`): each must keep the
        // in-memory role, or the device would paint the wave53-probe picture.
        val folded = com.styleconverter.runtime.content.PseudoBoxFold.resolve(
            com.styleconverter.runtime.content.PseudoTextFold.resolve(
                com.styleconverter.runtime.core.renderer.ContentsUnboxing.resolve(syntheticTable)).component)
        val merged = folded.copy(properties = folded.properties)          // the mergedComponent shape
        assertTrue(TableBodyForest.isAnonymous(merged))
        assertEquals(TableCellHug.Chrome(stroke = false, hug = true), TableCellHug.chrome(merged, todaysStroke(merged)))
    }

    @Test
    fun declaredTableBodyRoot_keepsTodaysStroke_noHug() {
        // 006's own body-root (an empty declared TABLE): not anonymous.
        val body = rootsOf(s006)[0]
        assertEquals("body-root", body.role)
        assertEquals(TableCellHug.Chrome(stroke = true, hug = false), TableCellHug.chrome(body, todaysStroke(body)))
    }

    @Test
    fun declaredTable_percentageSizing003_keepsTodaysStroke_noHug() {
        // The declared `display: table` box (2-281) — the D1 rim stays (queued).
        val table = rootsOf(pct003).single { it.id.endsWith("__2-281") }
        assertEquals(TableCellHug.Chrome(stroke = true, hug = false), TableCellHug.chrome(table, todaysStroke(table)))
    }

    @Test
    fun uaTable_baselineEmptyCell001_noStroke_noHug() {
        // A UA `<table>`: today's expression is already false; no hug (the D2 shape stays, queued).
        val table = rootsOf(bec001).single { it._tag == "table" }
        assertEquals(false, todaysStroke(table))
        assertEquals(TableCellHug.Chrome(stroke = false, hug = false), TableCellHug.chrome(table, todaysStroke(table)))
    }

    @Test
    fun uaTable_containContent004_isTodaysExpression_noHug() {
        // L4's carrier: chrome must return (today's expression, false) — the pin behind PLAN §9 D15.
        val table = rootsOf(cc004).single { it._tag == "table" }
        assertEquals(TableCellHug.Chrome(stroke = todaysStroke(table), hug = false),
            TableCellHug.chrome(table, todaysStroke(table)))
    }

    @Test
    fun hugColumn_disabled_isTheReceiverItself() {
        // Byte-identity of every non-anonymous table's cell chain: no extra node.
        val m = Modifier.then(Modifier)
        assertSame(m, m.hugColumn(false))
        // …and enabled it really adds the intrinsic read.
        assertNotSame(m, m.hugColumn(true))
    }

    /** TableApplier.kt, found by walking up to the repo root (the SeamReachabilityTest walk-up). */
    private val applier: String by lazy {
        val anchor = "runtimes/compose/src/main/java/com/styleconverter/runtime/table/TableApplier.kt"
        var dir: File? = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (dir != null && !File(dir, anchor).exists()) dir = dir.parentFile
        File(requireNotNull(dir) { "repo root not found" }, anchor).readText()
    }

    @Test
    fun applierSource_tableProvidesTheHug_cellChainsHugBeforeFillMaxHeight() {
        // Table(…): the parameter with the frozen default, provided per table.
        assertTrue(applier.contains("cellsHugContent: Boolean = false,"))
        assertTrue(applier.contains("TableCellHug.LocalTableCellsHugContent provides cellsHugContent"))
        // TableCell: the hug sits between the cell's weight and fillMaxHeight.
        val cell = applier.substring(applier.indexOf("fun RowScope.TableCell("))
        val hug = cell.indexOf(".hugColumn(TableCellHug.LocalTableCellsHugContent.current)")
        val fill = cell.indexOf(".fillMaxHeight()")
        assertTrue("TableCell does not chain hugColumn", hug >= 0)
        assertTrue("hugColumn is not chained before fillMaxHeight", hug < fill)
        assertTrue(cell.indexOf(".then(cellModifier)") < hug)
    }
}
