// _dispatch.ts — Phase-6 typography dispatch.
// Centralises the 109 Extractor+Applier calls so StyleBuilder.ts remains
// readable.  Mirrors engine/borders/_dispatch.ts (Phase 5).
//
// Each property is a one-liner: run its extractor over the full IR list, pass
// the resulting config to its applier, and spread the emitted CSS into the
// accumulator.  Extractors are last-write-wins so call order doesn't matter.

import type { CSSProperties } from 'react';

// All 109 extractor/applier pairs, enumerated explicitly so `tsc --noEmit`
// catches import drift if any file is renamed or removed.
import { extractAlignmentBaseline } from './AlignmentBaselineExtractor';
import { applyAlignmentBaseline } from './AlignmentBaselineApplier';
import { extractBaselineShift } from './BaselineShiftExtractor';
import { applyBaselineShift } from './BaselineShiftApplier';
import { extractBaselineSource } from './BaselineSourceExtractor';
import { applyBaselineSource } from './BaselineSourceApplier';
import { extractBlockEllipsis } from './BlockEllipsisExtractor';
import { applyBlockEllipsis } from './BlockEllipsisApplier';
import { extractDirection } from './DirectionExtractor';
import { applyDirection } from './DirectionApplier';
import { extractDominantBaseline } from './DominantBaselineExtractor';
import { applyDominantBaseline } from './DominantBaselineApplier';
import { extractDominantBaselineAdjust } from './DominantBaselineAdjustExtractor';
import { applyDominantBaselineAdjust } from './DominantBaselineAdjustApplier';
import { extractFontDisplay } from './FontDisplayExtractor';
import { applyFontDisplay } from './FontDisplayApplier';
import { extractFontFamily } from './FontFamilyExtractor';
import { applyFontFamily } from './FontFamilyApplier';
import { extractFontFeatureSettings } from './FontFeatureSettingsExtractor';
import { applyFontFeatureSettings } from './FontFeatureSettingsApplier';
import { extractFontKerning } from './FontKerningExtractor';
import { applyFontKerning } from './FontKerningApplier';
import { extractFontLanguageOverride } from './FontLanguageOverrideExtractor';
import { applyFontLanguageOverride } from './FontLanguageOverrideApplier';
import { extractFontMaxSize } from './FontMaxSizeExtractor';
import { applyFontMaxSize } from './FontMaxSizeApplier';
import { extractFontMinSize } from './FontMinSizeExtractor';
import { applyFontMinSize } from './FontMinSizeApplier';
import { extractFontNamedInstance } from './FontNamedInstanceExtractor';
import { applyFontNamedInstance } from './FontNamedInstanceApplier';
import { extractFontOpticalSizing } from './FontOpticalSizingExtractor';
import { applyFontOpticalSizing } from './FontOpticalSizingApplier';
import { extractFontPalette } from './FontPaletteExtractor';
import { applyFontPalette } from './FontPaletteApplier';
import { extractFontSize } from './FontSizeExtractor';
import { applyFontSize } from './FontSizeApplier';
import { extractFontSizeAdjust } from './FontSizeAdjustExtractor';
import { applyFontSizeAdjust } from './FontSizeAdjustApplier';
import { extractFontSmooth } from './FontSmoothExtractor';
import { applyFontSmooth } from './FontSmoothApplier';
import { extractFontStretch } from './FontStretchExtractor';
import { applyFontStretch } from './FontStretchApplier';
import { extractFontStyle } from './FontStyleExtractor';
import { applyFontStyle } from './FontStyleApplier';
import { extractFontSynthesisPosition } from './FontSynthesisPositionExtractor';
import { applyFontSynthesisPosition } from './FontSynthesisPositionApplier';
import { extractFontSynthesisSmallCaps } from './FontSynthesisSmallCapsExtractor';
import { applyFontSynthesisSmallCaps } from './FontSynthesisSmallCapsApplier';
import { extractFontSynthesisStyle } from './FontSynthesisStyleExtractor';
import { applyFontSynthesisStyle } from './FontSynthesisStyleApplier';
import { extractFontSynthesisWeight } from './FontSynthesisWeightExtractor';
import { applyFontSynthesisWeight } from './FontSynthesisWeightApplier';
import { extractFontVariantAlternates } from './FontVariantAlternatesExtractor';
import { applyFontVariantAlternates } from './FontVariantAlternatesApplier';
import { extractFontVariantCaps } from './FontVariantCapsExtractor';
import { applyFontVariantCaps } from './FontVariantCapsApplier';
import { extractFontVariantEastAsian } from './FontVariantEastAsianExtractor';
import { applyFontVariantEastAsian } from './FontVariantEastAsianApplier';
import { extractFontVariantEmoji } from './FontVariantEmojiExtractor';
import { applyFontVariantEmoji } from './FontVariantEmojiApplier';
import { extractFontVariantLigatures } from './FontVariantLigaturesExtractor';
import { applyFontVariantLigatures } from './FontVariantLigaturesApplier';
import { extractFontVariantNumeric } from './FontVariantNumericExtractor';
import { applyFontVariantNumeric } from './FontVariantNumericApplier';
import { extractFontVariantPosition } from './FontVariantPositionExtractor';
import { applyFontVariantPosition } from './FontVariantPositionApplier';
import { extractFontVariationSettings } from './FontVariationSettingsExtractor';
import { applyFontVariationSettings } from './FontVariationSettingsApplier';
import { extractFontWeight } from './FontWeightExtractor';
import { applyFontWeight } from './FontWeightApplier';
import { extractGlyphOrientationHorizontal } from './GlyphOrientationHorizontalExtractor';
import { applyGlyphOrientationHorizontal } from './GlyphOrientationHorizontalApplier';
import { extractGlyphOrientationVertical } from './GlyphOrientationVerticalExtractor';
import { applyGlyphOrientationVertical } from './GlyphOrientationVerticalApplier';
import { extractHangingPunctuation } from './HangingPunctuationExtractor';
import { applyHangingPunctuation } from './HangingPunctuationApplier';
import { extractHyphenateCharacter } from './HyphenateCharacterExtractor';
import { applyHyphenateCharacter } from './HyphenateCharacterApplier';
import { extractHyphenateLimitChars } from './HyphenateLimitCharsExtractor';
import { applyHyphenateLimitChars } from './HyphenateLimitCharsApplier';
import { extractHyphenateLimitLast } from './HyphenateLimitLastExtractor';
import { applyHyphenateLimitLast } from './HyphenateLimitLastApplier';
import { extractHyphenateLimitLines } from './HyphenateLimitLinesExtractor';
import { applyHyphenateLimitLines } from './HyphenateLimitLinesApplier';
import { extractHyphenateLimitZone } from './HyphenateLimitZoneExtractor';
import { applyHyphenateLimitZone } from './HyphenateLimitZoneApplier';
import { extractHyphens } from './HyphensExtractor';
import { applyHyphens } from './HyphensApplier';
import { extractInitialLetter } from './InitialLetterExtractor';
import { applyInitialLetter } from './InitialLetterApplier';
import { extractInitialLetterAlign } from './InitialLetterAlignExtractor';
import { applyInitialLetterAlign } from './InitialLetterAlignApplier';
import { extractKerning } from './KerningExtractor';
import { applyKerning } from './KerningApplier';
import { extractLetterSpacing } from './LetterSpacingExtractor';
import { applyLetterSpacing } from './LetterSpacingApplier';
import { extractLineBreak } from './LineBreakExtractor';
import { applyLineBreak } from './LineBreakApplier';
import { extractLineClamp } from './LineClampExtractor';
import { applyLineClamp } from './LineClampApplier';
import { extractLineGrid } from './LineGridExtractor';
import { applyLineGrid } from './LineGridApplier';
import { extractLineHeight } from './LineHeightExtractor';
import { applyLineHeight } from './LineHeightApplier';
import { extractLineHeightStep } from './LineHeightStepExtractor';
import { applyLineHeightStep } from './LineHeightStepApplier';
import { extractLineSnap } from './LineSnapExtractor';
import { applyLineSnap } from './LineSnapApplier';
import { extractMaxLines } from './MaxLinesExtractor';
import { applyMaxLines } from './MaxLinesApplier';
import { extractOrphans } from './OrphansExtractor';
import { applyOrphans } from './OrphansApplier';
import { extractOverflowWrap } from './OverflowWrapExtractor';
import { applyOverflowWrap } from './OverflowWrapApplier';
import { extractQuotes } from './QuotesExtractor';
import { applyQuotes } from './QuotesApplier';
import { extractRubyAlign } from './RubyAlignExtractor';
import { applyRubyAlign } from './RubyAlignApplier';
import { extractRubyMerge } from './RubyMergeExtractor';
import { applyRubyMerge } from './RubyMergeApplier';
import { extractRubyOverhang } from './RubyOverhangExtractor';
import { applyRubyOverhang } from './RubyOverhangApplier';
import { extractRubyPosition } from './RubyPositionExtractor';
import { applyRubyPosition } from './RubyPositionApplier';
import { extractTabSize } from './TabSizeExtractor';
import { applyTabSize } from './TabSizeApplier';
import { extractTextAlign } from './TextAlignExtractor';
import { applyTextAlign } from './TextAlignApplier';
import { extractTextAlignAll } from './TextAlignAllExtractor';
import { applyTextAlignAll } from './TextAlignAllApplier';
import { extractTextAlignLast } from './TextAlignLastExtractor';
import { applyTextAlignLast } from './TextAlignLastApplier';
import { extractTextAnchor } from './TextAnchorExtractor';
import { applyTextAnchor } from './TextAnchorApplier';
import { extractTextAutospace } from './TextAutospaceExtractor';
import { applyTextAutospace } from './TextAutospaceApplier';
import { extractTextBoxEdge } from './TextBoxEdgeExtractor';
import { applyTextBoxEdge } from './TextBoxEdgeApplier';
import { extractTextBoxTrim } from './TextBoxTrimExtractor';
import { applyTextBoxTrim } from './TextBoxTrimApplier';
import { extractTextCombineUpright } from './TextCombineUprightExtractor';
import { applyTextCombineUpright } from './TextCombineUprightApplier';
import { extractTextDecorationColor } from './TextDecorationColorExtractor';
import { applyTextDecorationColor } from './TextDecorationColorApplier';
import { extractTextDecorationLine } from './TextDecorationLineExtractor';
import { applyTextDecorationLine } from './TextDecorationLineApplier';
import { extractTextDecorationSkip } from './TextDecorationSkipExtractor';
import { applyTextDecorationSkip } from './TextDecorationSkipApplier';
import { extractTextDecorationSkipInk } from './TextDecorationSkipInkExtractor';
import { applyTextDecorationSkipInk } from './TextDecorationSkipInkApplier';
import { extractTextDecorationStyle } from './TextDecorationStyleExtractor';
import { applyTextDecorationStyle } from './TextDecorationStyleApplier';
import { extractTextDecorationThickness } from './TextDecorationThicknessExtractor';
import { applyTextDecorationThickness } from './TextDecorationThicknessApplier';
import { extractTextEmphasis } from './TextEmphasisExtractor';
import { applyTextEmphasis } from './TextEmphasisApplier';
import { extractTextEmphasisColor } from './TextEmphasisColorExtractor';
import { applyTextEmphasisColor } from './TextEmphasisColorApplier';
import { extractTextEmphasisPosition } from './TextEmphasisPositionExtractor';
import { applyTextEmphasisPosition } from './TextEmphasisPositionApplier';
import { extractTextEmphasisStyle } from './TextEmphasisStyleExtractor';
import { applyTextEmphasisStyle } from './TextEmphasisStyleApplier';
import { extractTextGroupAlign } from './TextGroupAlignExtractor';
import { applyTextGroupAlign } from './TextGroupAlignApplier';
import { extractTextIndent } from './TextIndentExtractor';
import { applyTextIndent } from './TextIndentApplier';
import { extractTextJustify } from './TextJustifyExtractor';
import { applyTextJustify } from './TextJustifyApplier';
import { extractTextOrientation } from './TextOrientationExtractor';
import { applyTextOrientation } from './TextOrientationApplier';
import { extractTextOverflow } from './TextOverflowExtractor';
import { applyTextOverflow } from './TextOverflowApplier';
import { extractTextRendering } from './TextRenderingExtractor';
import { applyTextRendering } from './TextRenderingApplier';
import { extractTextShadow } from './TextShadowExtractor';
import { applyTextShadow } from './TextShadowApplier';
import { extractTextSizeAdjust } from './TextSizeAdjustExtractor';
import { applyTextSizeAdjust } from './TextSizeAdjustApplier';
import { extractTextSpaceCollapse } from './TextSpaceCollapseExtractor';
import { applyTextSpaceCollapse } from './TextSpaceCollapseApplier';
import { extractTextSpaceTrim } from './TextSpaceTrimExtractor';
import { applyTextSpaceTrim } from './TextSpaceTrimApplier';
import { extractTextSpacing } from './TextSpacingExtractor';
import { applyTextSpacing } from './TextSpacingApplier';
import { extractTextSpacingTrim } from './TextSpacingTrimExtractor';
import { applyTextSpacingTrim } from './TextSpacingTrimApplier';
import { extractTextTransform } from './TextTransformExtractor';
import { applyTextTransform } from './TextTransformApplier';
import { extractTextUnderlineOffset } from './TextUnderlineOffsetExtractor';
import { applyTextUnderlineOffset } from './TextUnderlineOffsetApplier';
import { extractTextUnderlinePosition } from './TextUnderlinePositionExtractor';
import { applyTextUnderlinePosition } from './TextUnderlinePositionApplier';
import { extractTextWrap } from './TextWrapExtractor';
import { applyTextWrap } from './TextWrapApplier';
import { extractTextWrapMode } from './TextWrapModeExtractor';
import { applyTextWrapMode } from './TextWrapModeApplier';
import { extractTextWrapStyle } from './TextWrapStyleExtractor';
import { applyTextWrapStyle } from './TextWrapStyleApplier';
import { extractUnicodeBidi } from './UnicodeBidiExtractor';
import { applyUnicodeBidi } from './UnicodeBidiApplier';
import { extractVerticalAlign } from './VerticalAlignExtractor';
import { applyVerticalAlign } from './VerticalAlignApplier';
import { extractVerticalAlignLast } from './VerticalAlignLastExtractor';
import { applyVerticalAlignLast } from './VerticalAlignLastApplier';
import { extractWhiteSpace } from './WhiteSpaceExtractor';
import { applyWhiteSpace } from './WhiteSpaceApplier';
import { extractWhiteSpaceCollapse } from './WhiteSpaceCollapseExtractor';
import { applyWhiteSpaceCollapse } from './WhiteSpaceCollapseApplier';
import { extractWidows } from './WidowsExtractor';
import { applyWidows } from './WidowsApplier';
import { extractWordBreak } from './WordBreakExtractor';
import { applyWordBreak } from './WordBreakApplier';
import { extractWordSpaceTransform } from './WordSpaceTransformExtractor';
import { applyWordSpaceTransform } from './WordSpaceTransformApplier';
import { extractWordSpacing } from './WordSpacingExtractor';
import { applyWordSpacing } from './WordSpacingApplier';
import { extractWordWrap } from './WordWrapExtractor';
import { applyWordWrap } from './WordWrapApplier';
import { extractWritingMode } from './WritingModeExtractor';
import { applyWritingMode } from './WritingModeApplier';

interface IRPropertyLike { type: string; data: unknown }

// Run every typography extractor/applier and return a merged style object.
// Called once per component from `StyleBuilder.buildStyles` — replaces the
// legacy FontSize/FontWeight/LetterSpacing/etc. switch-case cluster.
export function applyTypographyPhase6(properties: IRPropertyLike[]): CSSProperties {
  const out: CSSProperties = {};

  // Each Object.assign is a one-shot fold; order only matters for the handful
  // of properties that double-emit keys (LineClamp emits display/overflow).
  // LineClamp is applied last so its -webkit-box shim doesn't get clobbered
  // by other typography rules that also touch `display` (none currently do).
  Object.assign(out, applyAlignmentBaseline(extractAlignmentBaseline(properties)));
  Object.assign(out, applyBaselineShift(extractBaselineShift(properties)));
  Object.assign(out, applyBaselineSource(extractBaselineSource(properties)));
  Object.assign(out, applyBlockEllipsis(extractBlockEllipsis(properties)));
  Object.assign(out, applyDirection(extractDirection(properties)));
  Object.assign(out, applyDominantBaseline(extractDominantBaseline(properties)));
  Object.assign(out, applyDominantBaselineAdjust(extractDominantBaselineAdjust(properties)));
  Object.assign(out, applyFontDisplay(extractFontDisplay(properties)));
  Object.assign(out, applyFontFamily(extractFontFamily(properties)));
  Object.assign(out, applyFontFeatureSettings(extractFontFeatureSettings(properties)));
  Object.assign(out, applyFontKerning(extractFontKerning(properties)));
  Object.assign(out, applyFontLanguageOverride(extractFontLanguageOverride(properties)));
  Object.assign(out, applyFontMaxSize(extractFontMaxSize(properties)));
  Object.assign(out, applyFontMinSize(extractFontMinSize(properties)));
  Object.assign(out, applyFontNamedInstance(extractFontNamedInstance(properties)));
  Object.assign(out, applyFontOpticalSizing(extractFontOpticalSizing(properties)));
  Object.assign(out, applyFontPalette(extractFontPalette(properties)));
  Object.assign(out, applyFontSize(extractFontSize(properties)));
  Object.assign(out, applyFontSizeAdjust(extractFontSizeAdjust(properties)));
  Object.assign(out, applyFontSmooth(extractFontSmooth(properties)));
  Object.assign(out, applyFontStretch(extractFontStretch(properties)));
  Object.assign(out, applyFontStyle(extractFontStyle(properties)));
  Object.assign(out, applyFontSynthesisPosition(extractFontSynthesisPosition(properties)));
  Object.assign(out, applyFontSynthesisSmallCaps(extractFontSynthesisSmallCaps(properties)));
  Object.assign(out, applyFontSynthesisStyle(extractFontSynthesisStyle(properties)));
  Object.assign(out, applyFontSynthesisWeight(extractFontSynthesisWeight(properties)));
  Object.assign(out, applyFontVariantAlternates(extractFontVariantAlternates(properties)));
  Object.assign(out, applyFontVariantCaps(extractFontVariantCaps(properties)));
  Object.assign(out, applyFontVariantEastAsian(extractFontVariantEastAsian(properties)));
  Object.assign(out, applyFontVariantEmoji(extractFontVariantEmoji(properties)));
  Object.assign(out, applyFontVariantLigatures(extractFontVariantLigatures(properties)));
  Object.assign(out, applyFontVariantNumeric(extractFontVariantNumeric(properties)));
  Object.assign(out, applyFontVariantPosition(extractFontVariantPosition(properties)));
  Object.assign(out, applyFontVariationSettings(extractFontVariationSettings(properties)));
  Object.assign(out, applyFontWeight(extractFontWeight(properties)));
  Object.assign(out, applyGlyphOrientationHorizontal(extractGlyphOrientationHorizontal(properties)));
  Object.assign(out, applyGlyphOrientationVertical(extractGlyphOrientationVertical(properties)));
  Object.assign(out, applyHangingPunctuation(extractHangingPunctuation(properties)));
  Object.assign(out, applyHyphenateCharacter(extractHyphenateCharacter(properties)));
  Object.assign(out, applyHyphenateLimitChars(extractHyphenateLimitChars(properties)));
  Object.assign(out, applyHyphenateLimitLast(extractHyphenateLimitLast(properties)));
  Object.assign(out, applyHyphenateLimitLines(extractHyphenateLimitLines(properties)));
  Object.assign(out, applyHyphenateLimitZone(extractHyphenateLimitZone(properties)));
  Object.assign(out, applyHyphens(extractHyphens(properties)));
  Object.assign(out, applyInitialLetter(extractInitialLetter(properties)));
  Object.assign(out, applyInitialLetterAlign(extractInitialLetterAlign(properties)));
  Object.assign(out, applyKerning(extractKerning(properties)));
  Object.assign(out, applyLetterSpacing(extractLetterSpacing(properties)));
  Object.assign(out, applyLineBreak(extractLineBreak(properties)));
  Object.assign(out, applyLineGrid(extractLineGrid(properties)));
  Object.assign(out, applyLineHeight(extractLineHeight(properties)));
  Object.assign(out, applyLineHeightStep(extractLineHeightStep(properties)));
  Object.assign(out, applyLineSnap(extractLineSnap(properties)));
  Object.assign(out, applyMaxLines(extractMaxLines(properties)));
  Object.assign(out, applyOrphans(extractOrphans(properties)));
  Object.assign(out, applyOverflowWrap(extractOverflowWrap(properties)));
  Object.assign(out, applyQuotes(extractQuotes(properties)));
  Object.assign(out, applyRubyAlign(extractRubyAlign(properties)));
  Object.assign(out, applyRubyMerge(extractRubyMerge(properties)));
  Object.assign(out, applyRubyOverhang(extractRubyOverhang(properties)));
  Object.assign(out, applyRubyPosition(extractRubyPosition(properties)));
  Object.assign(out, applyTabSize(extractTabSize(properties)));
  Object.assign(out, applyTextAlign(extractTextAlign(properties)));
  Object.assign(out, applyTextAlignAll(extractTextAlignAll(properties)));
  Object.assign(out, applyTextAlignLast(extractTextAlignLast(properties)));
  Object.assign(out, applyTextAnchor(extractTextAnchor(properties)));
  Object.assign(out, applyTextAutospace(extractTextAutospace(properties)));
  Object.assign(out, applyTextBoxEdge(extractTextBoxEdge(properties)));
  Object.assign(out, applyTextBoxTrim(extractTextBoxTrim(properties)));
  Object.assign(out, applyTextCombineUpright(extractTextCombineUpright(properties)));
  Object.assign(out, applyTextDecorationColor(extractTextDecorationColor(properties)));
  Object.assign(out, applyTextDecorationLine(extractTextDecorationLine(properties)));
  Object.assign(out, applyTextDecorationSkip(extractTextDecorationSkip(properties)));
  Object.assign(out, applyTextDecorationSkipInk(extractTextDecorationSkipInk(properties)));
  Object.assign(out, applyTextDecorationStyle(extractTextDecorationStyle(properties)));
  Object.assign(out, applyTextDecorationThickness(extractTextDecorationThickness(properties)));
  Object.assign(out, applyTextEmphasis(extractTextEmphasis(properties)));
  Object.assign(out, applyTextEmphasisColor(extractTextEmphasisColor(properties)));
  Object.assign(out, applyTextEmphasisPosition(extractTextEmphasisPosition(properties)));
  Object.assign(out, applyTextEmphasisStyle(extractTextEmphasisStyle(properties)));
  Object.assign(out, applyTextGroupAlign(extractTextGroupAlign(properties)));
  Object.assign(out, applyTextIndent(extractTextIndent(properties)));
  Object.assign(out, applyTextJustify(extractTextJustify(properties)));
  Object.assign(out, applyTextOrientation(extractTextOrientation(properties)));
  Object.assign(out, applyTextOverflow(extractTextOverflow(properties)));
  Object.assign(out, applyTextRendering(extractTextRendering(properties)));
  Object.assign(out, applyTextShadow(extractTextShadow(properties)));
  Object.assign(out, applyTextSizeAdjust(extractTextSizeAdjust(properties)));
  Object.assign(out, applyTextSpaceCollapse(extractTextSpaceCollapse(properties)));
  Object.assign(out, applyTextSpaceTrim(extractTextSpaceTrim(properties)));
  Object.assign(out, applyTextSpacing(extractTextSpacing(properties)));
  Object.assign(out, applyTextSpacingTrim(extractTextSpacingTrim(properties)));
  Object.assign(out, applyTextTransform(extractTextTransform(properties)));
  Object.assign(out, applyTextUnderlineOffset(extractTextUnderlineOffset(properties)));
  Object.assign(out, applyTextUnderlinePosition(extractTextUnderlinePosition(properties)));
  Object.assign(out, applyTextWrap(extractTextWrap(properties)));
  Object.assign(out, applyTextWrapMode(extractTextWrapMode(properties)));
  Object.assign(out, applyTextWrapStyle(extractTextWrapStyle(properties)));
  Object.assign(out, applyUnicodeBidi(extractUnicodeBidi(properties)));
  Object.assign(out, applyVerticalAlign(extractVerticalAlign(properties)));
  Object.assign(out, applyVerticalAlignLast(extractVerticalAlignLast(properties)));
  Object.assign(out, applyWhiteSpace(extractWhiteSpace(properties)));
  Object.assign(out, applyWhiteSpaceCollapse(extractWhiteSpaceCollapse(properties)));
  Object.assign(out, applyWidows(extractWidows(properties)));
  Object.assign(out, applyWordBreak(extractWordBreak(properties)));
  Object.assign(out, applyWordSpaceTransform(extractWordSpaceTransform(properties)));
  Object.assign(out, applyWordSpacing(extractWordSpacing(properties)));
  Object.assign(out, applyWordWrap(extractWordWrap(properties)));
  Object.assign(out, applyWritingMode(extractWritingMode(properties)));
  // LineClamp stamped last because it writes display + overflow as a shim.
  Object.assign(out, applyLineClamp(extractLineClamp(properties)));

  return out;
}
